# Dev Services demarre automatiquement un broker Kafka en mode dev/test
# (rien a configurer en local, Quarkus s'en charge)

# Canal sortant : le corbeau quitte la taverne avec son message
mp.messaging.outgoing.raven-outbound.connector=smallrye-kafka
mp.messaging.outgoing.raven-outbound.topic=raven-roost
mp.messaging.outgoing.raven-outbound.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

# Canal entrant : le corbeau se pose au colombier et delivre son message
mp.messaging.incoming.raven-inbound.connector=smallrye-kafka
mp.messaging.incoming.raven-inbound.topic=raven-roost
mp.messaging.incoming.raven-inbound.value.deserializer=fr.eletutour.tavern.raven.RavenMessageDeserializer
mp.messaging.incoming.raven-inbound.auto.offset.reset=earliest

# Gestion des erreurs : Envoi vers la Dead Letter Queue (DLQ) après échecs de traitement
mp.messaging.incoming.raven-inbound.failure-strategy=dead-letter-queue
mp.messaging.incoming.raven-inbound.dead-letter-queue.topic=raven-roost-dlq
mp.messaging.incoming.raven-inbound.dead-letter-queue.key.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.incoming.raven-inbound.dead-letter-queue.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

quarkus.application.name=kafka-quarkus-tavern
