{
 "title": "Tavern Advanced Overview",
 "tags": [
  "observability",
  "quarkus",
  "tavern"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Order Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(tavern_advanced_order_count_total[1m]))",
     "legendFormat": "Orders/sec"
    }
   ]
  },
  {
   "title": "Order Latency p95",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(tavern_advanced_order_seconds_bucket[2m])) by (le))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "API Availability",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(up{job=\"observabilite-advanced-tutorial\"})"
    }
   ]
  }
 ]
}