# Configuration de la base de données H2 (en mémoire pour le tuto)
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:tavern_db
quarkus.hibernate-orm.schema-management.strategy=drop-and-create

# Port spécifique pour éviter les conflits
quarkus.http.port=8083

# Activation de la console H2
quarkus.h2.console=true
