quarkus.smallrye-openapi.path=/openapi
quarkus.swagger-ui.always-include=true

quarkus.smallrye-openapi.info-title=Tavern REST API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=Exemple d'API REST dans une taverne medievale.
