# Pagination
tavern.pagination.default-limit=10
tavern.pagination.default-first=10

# Limites de requête
quarkus.smallrye-graphql.instrumentation-query-complexity=150
quarkus.smallrye-graphql.instrumentation-query-depth=8
%dev.quarkus.smallrye-graphql.instrumentation-query-depth=20
%test.quarkus.smallrye-graphql.instrumentation-query-depth=20