quarkus.http.port=9000
quarkus.smallrye-graphql-client.taverne.url=http://localhost:8080/graphql

quarkus.log.category."io.smallrye.graphql.client".level=TRACE
quarkus.log.category."io.smallrye.graphql.client".min-level=TRACE